### ISSUE TITLE
Posterior post-processing for individual mode

### ISSUE THREAD

**Issue by lmauviard** [xpsi-group/xpsi#415] opened 2024-12-01 20:10 UTC
So far, all the posterior post-processing is done by drawing samples from `*equal_weight.dat`

This can be done on individual posterior modes by getting posterior samples from `*post_separate.dat`, an output of Multinest when using multi-mode. I suggest to add a possibility to do it in post-processing with a `modes` parameter when loading runs.

**Comment by thjsal** [comment] 2024-12-11 14:23
The pull request connected to this was not merged yet, so the issue is not yet closed?

**Comment by lmauviard** [comment] 2024-12-11 15:01
Ups, wrong manipulation

**Closed** 2024-12-13 10:39 UTC
Labels: enhancement, postprocessing, hackweek2024
