### ISSUE TITLE
Confirm `CustomInstrument` implementation in `module_generator`

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#92] opened 2022-09-19 12:43 UTC
There are certain portions which are commented out when the `CustomInstrument` scripts are generated. These are typically the bits that are required e.g. in the analysis of PSR J0437-4715. Check if any portions of the codes need to be removed and/or modified. 

@thjsal suspected the presence of a bug when XMM PN implementation is required. Check this.

**Comment by thjsal** [comment] 2022-09-19 12:45
Looks like the bug (found actually by Julia) with XMM PN in CustomInstrument is already corrected in module_generator, since otherwise I would expect to see it in this line:
https://github.com/xpsi-group/xpsi/blob/6b7c8d8430fb11716f0469e7dd16ec45ba3fd7c9/xpsi/module_generator.py#L3481
In the J0740 scripts for PN we have there max_input - min_input (instead of ARF.shape[0]) which does not work always.

**Comment by thjsal** [comment] 2022-09-19 12:52
But only now noticed that part of the code in module generator is actually commented. Need to look more into the code to see if it is working, since it looks very different from the scripts we have used so far.

**Comment by sguillot** [comment] 2023-02-02 09:12
@thjsal, @DevarshiChoudhury, What's the status of this bug ?

**Comment by thjsal** [comment] 2023-02-03 16:57
The issue is still not solved, as far as I know.

**Comment by thjsal** [comment] 2023-10-05 17:42
I think the main problem is that there is currently no CustomInstrument that would work for all different data formats ... And the module_generator cannot currently produce such general CustomInstrument either. 

The bug that we discussed seems in any case not likely to exist here, since it is indeed missing from that version of CustomInstrument where it used to be (the currently commented part of module generator). And the other version seems so different, that I don't see a reason to believe that it could have that same bug.

I think I would just close this issue.

**Closed** 2023-10-12 12:26 UTC
Labels: bug
