### ISSUE TITLE
Likelihood synthetise method broken

### ISSUE THREAD

**Issue by yveskini** [xpsi-group/xpsi#47] opened 2022-07-29 14:55 UTC
The likelihood synthesise method return none ( hence does not synthesise data) when one of the parameters is not within the bounds instead of throwing a "StrictBoundsError" error.

**Comment by yveskini** [comment] 2022-11-30 19:10
@thjsal The error message that we put to fix  the issue is a bit misleading. In  fact, if a parameter vector p fails the compactness test for example, then prior(p) will still return -inf. The error message will  still print :'At least one of the parameters value is not within defined bound No synthesic data will be produced', even though all the parameters are within the strict bounds.

**Comment by thjsal** [comment] 2022-11-30 22:59
I guess it depends what you define to be meaning of word "bounds". I would think returning minus infinity from prior(p) means that the parameter vector is outside of the prior bounds.

**Comment by sguillot** [comment] 2022-12-01 07:29
I think @yveskini 's point is that the error message is misleading because the compactness is not part of the parameter list per se. So I could see this as being confusing for the users who has parameters (M and R) within the bounds but still this this error message.

**Comment by thjsal** [comment] 2022-12-10 09:43
I see. Should we then change
```
                  print('At least one of the parameter values is not within the defined bounds.\n \
                    No synthetic data will be produced.')
```
to
```
                  print('At least one of the parameter values is not within the defined bounds or the multi-dimensional prior conditions (regarding e.g. compactness of the star) are not fulfilled.\n \
                    No synthetic data will be produced.')
``` 
or something like that?

**Comment by sguillot** [comment] 2022-12-10 09:47
I guess this is much easier to have this new output message than tracking down whether it was a parameter or a prior condition that caused the -inf likelihood.

**Comment by thjsal** [comment] 2022-12-10 10:06
Well, tracking might be needed even after the new error message, but at least you will be then more aware that it can be either of these (parameter hard bounds or a prior condition) that causes the problem. I can update this message.

**Comment by sguillot** [comment] 2022-12-10 10:10
Let's update the message for now, and keep the issue open

**Comment by yveskini** [comment] 2022-12-10 10:13
@thjsal , Maybe a message like this: Warning: Prior check failed. Either one parameter is not within bounds or a requirement set in CustomPrior has failed. will be more clear

**Comment by thjsal** [comment] 2022-12-11 12:48
I updated the warning in pull request #188 . In order to close this issue, were you @sguillot hoping for a message that would directly tell whether or not it is caused by the hard bounds or by the CustomPrior conditions? I think currently doing that would require saving some extra information (or extra returned output) in the call function of Prior.py, to be able to separate these from what comes from the CustomPrior..... Although, the user who writes the CustomPrior might then still write the CustomPrior in a way which ruins this. So I am not sure if those changes would be worth doing. 

I'm thinking that the new error message from Yves could be already fine.

**Comment by thjsal** [comment] 2022-12-11 12:55
It might be actually impossible to separate these since in CustomPrior.py one can always overwrite the call function of Prior.py in whatever way that is wanted.

**Comment by thjsal** [comment] 2022-12-11 18:40
Actually, slowing likelihood calls is not a problem, since we talk about synthesise function that is only used for generating synthetic data and not at all during sampling, as far as I understand. ...

Anyway, I realized your suggestion is possible to do and thus updated the pull request. I tested that it works using the `Synthetic_data.ipynb` notebook in the `examples_fast` directory. Please let me know, if that looks ok to you. 

However, I noticed that in order for any prior checks to take even place, I had to add supply the prior object when creating the likelihood object there. If you forget to provide the prior object (like in our example notebook), you can still create synthetic data that is outside of your prior limits (since presumably you then have no other than the default priors, which will complain anyway if being outside of those). Was the idea to have the prior check done also in this example @yveskini ?

**Comment by thjsal** [comment] 2022-12-12 15:21
The problem was fixed in this commit: https://github.com/xpsi-group/xpsi/commit/4f09d2e21f8d1a9c3228970fda8df504401ce8aa.
The synthetic data example script was there also updated to take the CustomPrior into account.

**Closed by thjsal** 2022-12-12 15:21 UTC
Labels: bug, hackweek2022
