### ISSUE TITLE
Change is_secondary in Hot_region_complexity

### ISSUE THREAD

**Issue by daspushpita** [xpsi-group/xpsi#291] opened 2023-02-17 12:38 UTC
https://github.com/xpsi-group/xpsi/blob/ace8ec39e2ed7f59bd84ce99ec2014b9121abfe8/docs/source/Hot_region_complexity.ipynb

**Comment by thjsal** [comment] 2023-02-17 12:40
And what is the reason it needs to be changed?

**Comment by daspushpita** [comment] 2023-02-17 12:44
Because it is deprecated I guess?

**Comment by thjsal** [comment] 2023-03-09 15:04
I don't think it is deprecated yet. I thought it just that we want to deprecate it.

**Comment by thjsal** [comment] 2023-03-09 15:11
Okay, I see in the comment string (in `HotRegion.py`) that this `is_secondary` is indeed deprecated in the sense that it has exactly the same effect as if using `is_antiphased` keyword argument. But it principle, it should still work as it is meant to work, right?

**Comment by thjsal** [comment] 2024-10-25 10:40
I think it is fine to close this issue, since it is essentially a duplicate of the issues #296 and #323.

**Closed by thjsal** 2024-10-25 10:40 UTC
Labels: documentation
